vich_uploader:
    db_driver: orm

    mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
        illustration_file:
            uri_prefix: /public/uploads/
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        
        about_picture_file: 
            uri_prefix: /public/uploads/about
            upload_destination: '%upload_about_dir%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
